services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: "${DB_URL}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    restart: unless-stopped
